title: Matt Dilworth's Digital Portfolio
email: zappad.md@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I have put together this Portfolio showcasing the best of my art and works.
baseurl: ""  # If your repository is named `username.github.io`, leave this empty. For project pages, use "/repository-name".
twitter_username: RealtorMattD
github_username: JeffreyLebowsk1

# Build settings
# theme: minima
plugins:
  - jekyll-feed
include:
  - assets/gallery/*/*
exclude:
  - README.md
